### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by bieganowski**

### CODE REVIEW

**Review by giohappy — COMMENTED** [review]
@bieganowski are you going to add auth control (admin only can run commands) to this PR?

**Comment by bieganowski** [comment]
Initially, I thought about having another PR for it, but that's actually a good idea to include it here :+1: 
a change is pushed :)

**Comment by giohappy** [comment]
@bieganowski as dicussed by chat let's make the permission class configurable, and keep the Admin permission as the default.
We can add it to this PR, what do you think?

**Comment by bieganowski** [comment]
Sure, that shouldn't be a problem to add it to the initial PR

**Comment by bieganowski** [comment]
ok, the PR is updated with configurable permission classes under `settings.API_COMMANDS_PERMISSION_CLASSES`. By default it points at `rest_framework.permissions.IsAdminUser`

**Review by giohappy — APPROVED** [review]

**Pull request merged**
